// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiIJf8p4januqMlyLwKBzlNLvBinNVr18',
    appId: '1:816082488854:android:d8c1ae81c87a360684af37',
    messagingSenderId: '816082488854',
    projectId: 'hackon-bf7c5',
    storageBucket: 'hackon-bf7c5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgpCKZOjDCkcNHx_xS_tH6bKLKKLMJW48',
    appId: '1:816082488854:web:fd1e4771c1d8d03584af37',
    messagingSenderId: '816082488854',
    projectId: 'hackon-bf7c5',
    authDomain: 'hackon-bf7c5.firebaseapp.com',
    storageBucket: 'hackon-bf7c5.firebasestorage.app',
    measurementId: 'G-CG9SRPG07N',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgpCKZOjDCkcNHx_xS_tH6bKLKKLMJW48',
    appId: '1:816082488854:web:fd1e4771c1d8d03584af37',
    messagingSenderId: '816082488854',
    projectId: 'hackon-bf7c5',
    authDomain: 'hackon-bf7c5.firebaseapp.com',
    storageBucket: 'hackon-bf7c5.firebasestorage.app',
    measurementId: 'G-CG9SRPG07N',
  );

}